# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "VariantIQ"
client_id = "76a6c470e49bfbff80afe0dced5067f6"
application_url = "https://variantiq-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://variantiq-production.up.railway.app/auth/callback",
  "https://variantiq-production.up.railway.app/auth/shopify/callback",
  "https://variantiq-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false